name: Dotnet-Core-application-CI-CD-pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: 'goswamiapp001'
  PACKAGE_PATH: './publish'
  DOTNET_VERSION: '3.1.x'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Out Source Code from Repository
      uses: actions/checkout@v2
    
    - name: Setup dotnet Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}
    
    - name: Display dotnet Version
      run: dotnet --version

    - name: Install dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release --no-restore

    - name: Publish App for deployment
      run: dotnet publish --configuration Release --no-build --output ${{env.PACKAGE_PATH}}

#   - name: Deploy to Azure Webapps
#      uses: azure/webapp-deploy@v2
#      with:
#        app-name: ${{env. AZURE_WEBAPP_NAME}}
#        publish-profile: ${{secrets.AZUR_WEBAPP_PUBLISH_PROFILE}}
#       package: ${{env.PACKAGE_PATH}}
    
    - name: Publish Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: FirstDotnetCore Download
        path: ${{env.PACKAGE_PATH}}
      
    - name: Print Success Message
      run: echo "All Done OK"
